version: "3"

services:
  db:
    image: postgres:9.4
#    deploy:
#      replicas: 1
    volumes:
      - pgsql_data:/var/lib/postgresql/data:rw,Z
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoopwd
  odoo:
    build: ./odoo
    env_file:
      - ./odoo/saas_config
#    deploy:
#      replicas: 3
    volumes:
      - odoo_data:/var/lib/odoo:rw,Z
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/odoo.conf:/etc/odoo/odoo.conf:ro
    depends_on:
      - db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoopwd
#    ports:
#      - "8069"
  nginx:
    image: nginx:1.13
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/secrets/server.crt:/etc/ssl/nginx/server.crt:ro
      - ./nginx/secrets/server.key:/etc/ssl/nginx/server.key:ro
      - ./nginx/secrets/dhparam.pem:/etc/ssl/nginx/dhparam.pem:ro
    depends_on:
      - odoo
    links:
      - odoo
    ports:
      - 80:80
      - 443:443

volumes:
  pgsql_data:
  odoo_data:
